name: neopteenv
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - idna=3.10=pyhd8ed1ab_1
  - libcxx=17.0.6=he5c5206_4
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.5.2=he92f556_0
  - pip=25.1=pyhc872135_2
  - python=3.10.18=h19e8193_0
  - readline=8.2=h1a28f6b_0
  - setuptools=78.1.1=py310hca03da5_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.14=h6ba3021_1
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - alembic==1.13.1
      - blinker==1.9.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - click==8.1.7
      - flask==2.2.5
      - flask-dance==6.2.0
      - flask-debugtoolbar==0.13.1
      - flask-login==0.6.3
      - flask-migrate==4.0.5
      - flask-sqlalchemy==3.1.1
      - flask-wtf==1.1.1
      - infinity==1.5
      - intervals==0.9.2
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - mako==1.3.10
      - markupsafe==2.1.5
      - oauthlib==3.2.2
      - python-dateutil==2.9.0.post0
      - python-editor==1.0.4
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - six==1.17.0
      - sqlalchemy==2.0.30
      - sqlalchemy-utils==0.41.2
      - typing-extensions==4.14.1
      - urllib3==2.5.0
      - urlobject==3.0.0
      - validators==0.35.0
      - werkzeug==2.2.3
      - wtforms==3.1.2
      - wtforms-components==0.11.0
prefix: /opt/anaconda3/envs/neopteenv
